// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Atcommands
 * Place the definition of custom atcommands in this file.
 * Format:
 *	ACMD_DEF(command_name),
 **/

//ACMD_DEF(newcommand),

// Battleground Extended by Vykimo
ACMD_DEF(bgstart),
ACMD_DEF(bgend),
ACMD_DEF(guildskill),
ACMD_DEF(listenbg),
ACMD_DEF(order),
ACMD_DEF(leader),
//ACMD_DEF(voteleader),
ACMD_DEF(reportafk),
ACMD_DEF2("votekick", reportafk),